__author__ = "Quentin Soubeyran"
__copyright__ = "Copyright 2020, Quentin Soubeyran"
__license__ = "MIT"
__version__ = "1.0a1"
__name__ = "pheres"
py_version = "3.8"
project_url="https://github.com/QuentinSoubeyran/pheres"